Repository rlemaitre/pillars, pull requests merged in 2024-03, with the labels that each got.

#72 feat(db): #57 Add DB migration module
  .tool-versions
  build.sbt
  modules/core/src/main/scala/pillars/Pillars.scala
  modules/core/src/main/scala/pillars/modules.scala
  modules/core/src/main/scala/pillars/package.scala
  modules/core/src/test/scala/pillars/TopologicalSortSuite.scala
  modules/db-migration/src/main/resources/META-INF/services/pillars.Loader
  modules/db-migration/src/main/scala/pillars/db/migrations/migrations.scala
  modules/db/src/main/scala/pillars/db/db.scala
  modules/docs/src/docs/user-guide/10_quick-start.adoc
  modules/docs/src/docs/user-guide/30_modules/10_db.adoc
  modules/docs/src/docs/user-guide/30_modules/15_db-migration.adoc
  modules/example/src/main/resources/config.yaml
  modules/example/src/main/resources/db/migrations/V001__init.sql
  modules/example/src/main/scala/example/app.scala
  modules/flags/src/main/scala/pillars/flags/FlagManager.scala
  modules/http-client/src/main/scala/pillars/httpclient/httpclient.scala
  project/Dependencies.scala
Labels: enhancement

#73 Patches/Minor updates
  build.sbt
Labels: dependency-update

#76 Patches/Minor updates
  project/Dependencies.scala
Labels: dependency-update

#77 Patches/Minor updates
  project/Dependencies.scala
Labels: dependency-update

#78 Rlemaitre/feat/add doobie module
  build.sbt
  modules/db-doobie/src/main/scala/pillars/db_doobie/db.scala
  modules/docs/src/docs/user-guide/30_modules/10_db.adoc
  project/Dependencies.scala
Labels: documentation, enhancement

#91 Patches/Minor updates
  project/Dependencies.scala
Labels: dependency-update

#90 ⬆️ Update doobie-core, doobie-hikari from 1.0.0-RC4 to 1.0.0-RC5
  project/Dependencies.scala
Labels: dependency-update
