Repository rlemaitre/pillars, pull requests merged in 2024-01, with the labels that each got.

#19 Update client3:core to 3.9.2
  project/Dependencies.scala
Labels: dependency-update

#20 Update tapir-http4s-client, ... to 1.9.6
  project/Dependencies.scala
Labels: dependency-update

#21 Update iron-scalacheck to 2.4.0
  project/Dependencies.scala
Labels: dependency-update

#25 Update scalafmt-core to 3.7.17
  .scalafmt.conf
Labels: dependency-update

#22 Update opentelemetry-exporter-otlp, ... to 1.34.1
  project/Dependencies.scala
Labels: dependency-update

#23 Update http4s-circe, http4s-core, ... to 0.23.25
  project/Dependencies.scala
Labels: dependency-update

#24 Update http4s-netty-client, ... to 0.5.12
  project/Dependencies.scala
Labels: dependency-update

#40 ⬆️ Update skunk-circe, skunk-core from 1.1.0-M2 to 1.1.0-M3
  project/Dependencies.scala
Labels: dependency-update

#27 ⬆️ Update otel4s-java from 0.3.0 to 0.4.0
  project/Dependencies.scala
Labels: dependency-update

#42 ✨ feat: Better DX for HTTP Client and DB
  build.sbt
  modules/core/src/main/scala/pillars/Pillars.scala
  modules/core/src/main/scala/pillars/app.scala
  modules/db/src/main/scala/pillars/db/db.scala
  modules/docs/src/docs/user-guide/20_features/30_probes.adoc
  modules/docs/src/docs/user-guide/20_features/40_api-server.adoc
  modules/docs/src/docs/user-guide/20_features/60_admin-server.adoc
  modules/docs/src/docs/user-guide/30_modules/10_db.adoc
  modules/docs/src/docs/user-guide/30_modules/20_http-client.adoc
  modules/docs/src/docs/user-guide/30_modules/30_flags.adoc
  modules/example/src/main/scala/example/app.scala
  modules/flags/src/main/scala/pillars/flags/package.scala
  modules/http-client/src/main/scala/pillars/httpclient/httpclient.scala
Labels: documentation, enhancement

#43 🔨 refactor(core): Introduce AppInfo to ease app declaration
  .scalafix.conf
  build.sbt
  modules/core/src/main/scala/pillars/Observability.scala
  modules/core/src/main/scala/pillars/app.scala
  modules/db/src/main/scala/pillars/db/db.scala
  modules/docs/src/docs/user-guide/10_quick-start.adoc
  modules/docs/src/docs/user-guide/index.adoc
  modules/example/src/main/resources/config.yaml
  modules/example/src/main/scala/example/app.scala
  modules/flags/src/main/scala/pillars/flags/FlagManager.scala
  project/plugins.sbt
Labels: documentation, enhancement

#44 Patches/Minor updates
  project/Dependencies.scala
Labels: dependency-update

#45 📚 docs(core): 31 Add documentation for configuration
  modules/core/src/main/scala/pillars/AdminServer.scala
  modules/core/src/main/scala/pillars/ApiServer.scala
  modules/core/src/main/scala/pillars/HttpServer.scala
  modules/core/src/main/scala/pillars/Observability.scala
  modules/core/src/main/scala/pillars/config.scala
  modules/db/src/main/scala/pillars/db/db.scala
  modules/docs/src/docs/user-guide/20_features/10_configuration.adoc
  modules/example/src/main/resources/config.yaml
Labels: documentation

#46 📚 docs(core): #32 Add documentation for logging
  .better-commits.json
  modules/docs/src/docs/user-guide/20_features/10_configuration.adoc
  modules/docs/src/docs/user-guide/20_features/20_logging.adoc
Labels: documentation

#48 📚 docs(core): #34 Add documentation for admin server
  modules/core/src/main/scala/pillars/app.scala
  modules/docs/src/docs/user-guide/20_features/60_admin-server.adoc
  modules/docs/src/docs/user-guide/30_modules/30_flags.adoc
Labels: documentation

#49 📚 docs(core): #47 Add documentation for probes
  modules/core/src/main/scala/pillars/probes.scala
  modules/docs/src/docs/user-guide/20_features/30_probes.adoc
Labels: documentation

#53 Patches/Minor updates
  project/Dependencies.scala
Labels: dependency-update
